services:
  web:
    build: .
    ports:
      - 8081:8081
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - docs/
        - action: rebuild
          path: package.json
  couchdb:
    image: couchdb:3.4.2
    ports:
      - 5984:5984
    env_file: ".env"
    volumes:
      - ./local.ini:/opt/couchdb/etc/local.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5984"]
      interval: 5s
      retries: 5
      start_period: 20s
  db-init:
    image: curlimages/curl:latest
    env_file: ".env"
    depends_on:
      couchdb:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        curl -u "$COUCHDB_USER:$COUCHDB_PASSWORD" -X PUT http://couchdb:5984/_users
        curl -u "$COUCHDB_USER:$COUCHDB_PASSWORD" -X PUT http://couchdb:5984/shopping-list
