services:
  couchdb :
    image: couchdb:2.1
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5984"]
      interval: 5s
      retries: 5
      start_period: 20s
  db-init:
    image: curlimages/curl:latest
    depends_on:
      couchdb:
        condition: service_healthy
    command: ["sh", "-c", "curl -X PUT http://couchdb:5984/shopping-list"]
