services:
  couchdb :
    image: couchdb:2.1
    ports:
      - 5984:5984
    env_file: ".env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5984"]
      interval: 5s
      retries: 5
      start_period: 20s
  db-init:
    image: curlimages/curl:latest
    env_file: ".env"
    depends_on:
      couchdb:
        condition: service_healthy
    command: >
      sh -c "
      curl -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/shopping-list &&
      curl -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/_node/nonode@nohost/_config/httpd/enable_cors -d '\"true\"' &&
      curl -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/_node/nonode@nohost/_config/cors/origins -d '\"*\"' &&
      curl -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/_node/nonode@nohost/_config/cors/methods -d '\"GET, POST, PUT, DELETE, OPTIONS\"' &&
      curl -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/_node/nonode@nohost/_config/cors/headers -d '\"accept, authorization, content-type, origin\"' &&
      curl -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT http://couchdb:5984/_node/nonode@nohost/_config/cors/credentials -d '\"true\"'
      "
